Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sushi"
authors = [{name = "TheHeadmaster"}]
dynamic = ["version", "description"]
